# **EDA House Price Predection**

In [3]:
# Loading Dataset 

import pandas as pd 
from pathlib import Path

DATASET_PATH = Path("C:\\Users\\boddu\OneDrive\Documents\Machine Learning\Multiple Linear Regression\House Price Prediction\data\house_price.csv")
df = pd.read_csv(DATASET_PATH)

In [6]:
# Viewing Shape and Head of Dataset
print("Shape of Dataset: ",df.shape)
print("Viewing First  Dataset Observations")
df.head()

Shape of Dataset:  (5000, 10)
Viewing First  Dataset Observations

,Area_sqft,Bedrooms,Bathrooms,Age_years,Floors,Location,Distance_to_City_km,HasGarage,School_Rating,Price
0,1473.9,2,2.0,1,1,Suburban,7.6,Yes,8.3,276000
1,1188.7,2,2.0,10,3,Rural,33.3,Yes,7.1,190100
2,2295.2,4,3.0,10,2,Rural,21.8,Yes,7.4,344300
3,1425.0,3,2.0,29,1,Suburban,11.9,Yes,4.9,264300
4,2037.9,2,1.0,3,1,Suburban,13.5,Yes,5.6,335100

In [7]:
# keeping the raw dataset safe in another variable called df_raw
df_raw = df.copy()

In [9]:
# Separating X(Feature) and y(target)

X = df.drop(
    columns="Price"
)

y = df["Price"]

print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

Shape of X: (5000, 9)
Shape of y: (5000,)

In [ ]:
# Train and Test Split Dataset 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [11]:
print(f"Shape of X_train: {X_train}")
print(f"Shape of X_test: {X_test}")
print(f"Shape of y_train: {y_train}")
print(f"Shape of y_test: {y_test}")

Shape of X_train:       Area_sqft  Bedrooms  Bathrooms  Age_years  Floors  Location  \
4227     1328.4         2        2.0          6       1     Rural
4676     1510.8         3        3.0          3       1  Suburban
800      1552.1         2        1.0         43       2  Downtown
3671     1514.3         2        2.0         16       1  Suburban
4193     1581.7         3        1.0          3       1     Rural
...         ...       ...        ...        ...     ...       ...
4426     1178.1         2        1.0          3       2  Suburban
466      2080.1         4        3.0         10       1  Downtown
3092     1922.6         2        1.0         37       1  Suburban
3772     1503.9         3        2.0          2       1  Downtown
860      1442.6         2        1.0         17       3  Downtown

      Distance_to_City_km HasGarage  School_Rating
4227                 33.6       Yes       5.800000
4676                  9.7       Yes       6.800000
800                   6.8       Yes       6.194723
3671                 10.7       Yes       7.100000
4193                 35.0       Yes       5.000000
...                   ...       ...            ...
4426                 11.7       Yes       6.100000
466                   0.2        No       8.562914
3092                 10.7       Yes       5.900000
3772                  0.2       Yes       9.361652
860                   2.4       Yes       8.287119

[4000 rows x 9 columns]
Shape of X_test:       Area_sqft  Bedrooms  Bathrooms  Age_years  Floors  Location  \
1501     1489.7         2        2.0          2       1     Rural
2586     1874.8         3        2.0         15       1  Suburban
2653     2744.4         5        3.0          2       3  Suburban
1055     1851.8         3        1.0          4       2     Rural
705      1364.7         3        2.0          2       1     Rural
...         ...       ...        ...        ...     ...       ...
4711     2092.9         4        3.0         17       1  Downtown
2313      976.9         2        1.0          5       1     Rural
3214     2967.7         6        4.0         20       2  Suburban
2732     2771.5         6        4.0         13       1  Downtown
1926     1485.7         3        2.0          1       1     Rural

      Distance_to_City_km HasGarage  School_Rating
1501                 22.9       Yes       7.900000
2586                 11.4       Yes       7.300000
2653                  8.1       Yes      10.000000
1055                 30.0       Yes       5.800000
705                  33.0       Yes       9.700000
...                   ...       ...            ...
4711                  3.0        No      10.000000
2313                 34.3       Yes       3.600000
3214                 14.3       Yes       7.600000
2732                  7.2        No       8.943359
1926                 23.5        No       6.600000

[1000 rows x 9 columns]
Shape of y_train: 4227    214000
4676    336500
800     298100
3671    315900
4193    234500
         ...
4426    234100
466     471600
3092    300100
3772    318300
860     312100
Name: Price, Length: 4000, dtype: int64
Shape of y_test: 1501    242200
2586    354000
2653    477000
1055    262400
705     235200
         ...
4711    444800
2313    155100
3214    487800
2732    506300
1926    233100
Name: Price, Length: 1000, dtype: int64

In [12]:
df.head()

,Area_sqft,Bedrooms,Bathrooms,Age_years,Floors,Location,Distance_to_City_km,HasGarage,School_Rating,Price
0,1473.9,2,2.0,1,1,Suburban,7.6,Yes,8.3,276000
1,1188.7,2,2.0,10,3,Rural,33.3,Yes,7.1,190100
2,2295.2,4,3.0,10,2,Rural,21.8,Yes,7.4,344300
3,1425.0,3,2.0,29,1,Suburban,11.9,Yes,4.9,264300
4,2037.9,2,1.0,3,1,Suburban,13.5,Yes,5.6,335100

In [13]:
# Identify feature type

numeric_features=[
    "Area_sqft",
    "Bedrooms",
    "Bathrooms",
    "Age_years",
    "Floors",
    "Distance_to_City_km",
    "School_Rating"
]

categorial_feature = [
    "Location",
    "HasGarage"
]

In [14]:
from sklearn.impute import SimpleImputer

numeric_imputer = SimpleImputer(
    strategy="median"
)